### ISSUE TITLE
Resolve t.co URLs

### ISSUE THREAD

**Issue by sergeychernyshev** [sergeychernyshev/web-speed-bot#6]
Resolve URLs shortened by Twitter or other apps.

E.g. URL can be shortened first by bit.ly and than by t.co. Both should be resolved.

![Image](https://i.imgur.com/qsr8iD5.jpg)

**Comment by PatMusi** [comment]
@sergeychernyshev Pull Request #7 should solve this problem.

**Comment by sergeychernyshev** [comment]
Merged. Can I test it live? ;)

**Comment by sergeychernyshev** [comment]
Tested and works!
